variant-inc/react-native-variant-chat

src/lib/Freshchat/Freshchat.ts
Problem
=======
- Apply request timeout to all HTTP calls
Solution
========
- Added the request timeout in the axios calls
=> Apply request timeout to all HTTP calls

src/hooks/useFreshchat.ts, src/lib/Exception.js, src/lib/Freshchat/Freshchat.ts, src/theme/constants.ts
Problem
=======
Not handling Freshchat status errors
Solution
========
Consider Freshchat response status for error handling
=> Improved error handling for Freshchat

src/store/selectors/freshchatSelectors.ts, src/store/slices/chat/chat.ts
Problem
=======
The redux store only support a single chat message channel
Solution
========
Change the redux state to index stored messages by chat channel name
=> Add multi-tenant chat message support

src/hooks/useFreshchat.ts
Problem
=======
- Fixes the issue for the failed message
Solution
========
- Fixed the issue for the failed message
=> Fixes the issue for the failed message

package.json, src/components/Bubble.tsx, src/components/Chat.tsx, src/components/MessagePdf.tsx, src/hooks/useApolloClient.ts, src/hooks/useFreshchat.ts, src/index.js, src/lib/Event.ts, src/lib/Exception.js, src/lib/Exception.ts, src/lib/Freshchat/Freshchat.ts, src/lib/VariantChat.ts, src/store/index.ts, src/store/selectors/freshchatSelectors.ts, src/store/slices/chat/chat.ts, src/types/VariantChat.d.ts
Remove component initialization from the UI component into a new custom hook.
Update component interface for handling multiple channels.
=> Refactor initialization into a separate custom hook

.github/workflows/tests.yml, package-lock.json, package.json, src/components/Chat.tsx, src/components/VariantChat.tsx, src/hooks/useFreshchat.ts, src/index.js, src/lib/Freshchat/Freshchat.ts, src/lib/VariantChat.ts, src/store/initialStoreState.ts, src/store/rootReducer.ts, src/store/selectors/freshchatSelectors.ts, src/store/slices/chat/chat.ts, src/types/Freshchat.ts, src/types/FreshchatConversationInfo.ts, src/types/FreshchatInit.enum.ts, src/types/Message.interface.ts, src/types/VariantChat.d.ts, src/types/VariantChatState.ts, src/types/custom.d.ts
Problem
=======
- Fixes a few issues
Solution
========
- Fixed the limit issue
=> Fixed a few issues

src/hooks/useFreshchat.ts, src/index.js
Problem
=======
Type was unusable
Solution
========
Export the type so it is usable
=> Fix type export for VariantChatState

README.md, src/components/Actions.tsx, src/hooks/useFreshchat.ts, src/index.js, src/lib/Freshchat/Freshchat.ts, src/types/VariantChatEvent.ts
Problem
=======
Library is interacting with the UI in an unexpected way.
Solution
========
Remove all Alerts and replace with event emitters.
=> Remove alerts and improve events implementation

src/hooks/useFreshchat.ts, src/lib/Freshchat/Freshchat.ts, src/types/FreshchatConversationInfo.ts
=> Minor logging updates

src/hooks/useFreshchat.ts, src/index.js, src/store/slices/chat/chat.ts
Problem
=======
Implements the reset of the chat reducer
Solution
========
- Implemented the reset of the chat reducer
=> Implements the reset functionality of the chat reducer

src/hooks/useFreshchat.ts, src/index.js, src/lib/Freshchat/Freshchat.ts, src/lib/VariantChat.ts, src/store/selectors/freshchatSelectors.ts, src/store/slices/chat/chat.ts, src/types/DriverStatus.ts, src/types/FreshchatConversationInfo.ts, src/types/VariantChatState.ts
Add driver status awareness to be used for performance tuning (at least).
=> Add driver status awareness

README.md, src/components/Actions.tsx
Problem
=======
Emitting an event for no reason.
Solution
========
Remove event emitter and replace nyi notice with a simple Alert
=> Remove the nyi event and just add Alert placeholders

src/index.ts
Handled internally now. No need for export.
=> Remove export resetVariantChat

src/index.ts
Export the main initialization config type
=> Export the interface config type

src/components/Chat.tsx, src/hooks/useApolloClient.ts, src/hooks/useFreshchat.ts, src/index.ts, src/lib/Freshchat/Freshchat.ts, src/theme/constants.ts, src/types/EventMessageType.enum.ts, src/types/EventName.enum.ts, src/types/VariantChatEvent.ts
Problem
=======
Updates the event name and message type
Solution
========
- Updated the event name and message type
=> Updates the event name and message type

.github/workflows/lint.yml, src/lib/Freshchat/Freshchat.ts, src/types/EventMessageType.enum.ts, src/types/EventName.enum.ts
Problem
=======
There is no request logging.
[link to JIRA RGR-609](https://usxtech.atlassian.net/browse/RGR-609)
[link to JIRA RGR-610](https://usxtech.atlassian.net/browse/RGR-610)
Solution
========
Add an axios interceptor to emit a log statement on all requests.
=> RGR-609 RGR-610 Log every http request

src/lib/Freshchat/Freshchat.ts
Problem
=======
- Filters the request data in the axios
Solution
========
- Filtered the request data in the axios.
=> Filters the request data in the axios

src/hooks/useFreshchat.ts, src/lib/Freshchat/Freshchat.ts, src/lib/Freshchat/FreshchatConversation.ts
Problem
=======
- Fix the issue for some user / agent requests
- Fix the no conversation issue
- Fix an endless loop of emitting unread message counts
Solution
========
- Fixed the issue for some user / agent requests
- Fixed the no conversation issue
- Fixed an endless loop of emitting unread message counts
=> Fixes the user / agent request issue and no conversation issue

src/hooks/useFreshchat.ts, src/lib/Freshchat/Freshchat.ts
Problem
=======
Raising unhandled exceptions and causing errors when conversation info is null.
Solution
========
Add exception and error handling.
=> Handle exceptions when conversation data is null

package-lock.json, package.json, src/hooks/useApolloClient.ts, src/lib/Freshchat/FreshchatConversation.ts
Problem
=======
- Sets the timeout in the Apollo request
Solution
========
- Implemented the timeout in the Apollo request
=> Sets the timeout in the Apollo request

src/components/Chat.tsx, src/theme/colors.ts, src/theme/paperTheme.ts, src/types/custom.d.ts
Problem
=======
[link to JIRA RGR-634](https://usxtech.atlassian.net/browse/RGR-634)
Solution
========
Added link support
=> [RGR-634] Added link support

src/components/Bubble.tsx, src/theme/colors.ts
Problem
=======
- Formatting sent, read and failed to send messages
link to JIRA RGR-655](https://usxtech.atlassian.net/browse/RGR-655)
Solution
========
- Updated the bubble formats
=> RGR-655 Formatting sent, read and failed to send messages

src/store/selectors/freshchatSelectors.ts
Problem
=======
- When a failed messages is attempted to resend it does not work
[link to JIRA RGR-654](https://usxtech.atlassian.net/browse/RGR-654)
Solution
========
- Fixed the resend issue for the failed message
=> RGR-654 Fixes the resend issue for the failed message

src/components/Chat.tsx
Problem
=======
- Fixes the underline issue
Solution
========
- Fixed the underline issue
=> Fixes the underline issue

src/components/Avatar.tsx, src/components/Chat.tsx
Problem
=======
- Updates alignment of name and avatar 
[link to JIRA RGR-656](https://usxtech.atlassian.net/browse/RGR-656)
Solution
========
- Updated alignment of name and avatar 
=> RGR-656 Alignment of name and avatar 

README.md
Follow-up PR to update ReadMe after merging RGR-657 original PR
=> Updating ReadMe with info about UrgentMessageComponent

src/components/Chat.tsx, src/store/selectors/freshchatSelectors.ts
Problem
=======
- Several tap to open Image file on Platform Science 
[link to JIRA RGR-663](https://usxtech.atlassian.net/browse/RGR-663)
Solution
========
- Cleaned up the LightBox
- Fixed more loading issue 
=> RGR-663 Several tap to open Image file on Platform Science 

src/components/VariantChat.tsx, src/hooks/useApolloClient.ts, src/lib/Freshchat/Freshchat.ts
Problem
=======
It takes the messaging api service longer to create conversations than the time the app waits.
[link to JIRA RGR-677](https://usxtech.atlassian.net/browse/RGR-677)
Solution
========
Increase both Axios and GraphQL timeout.
=> RGR-677 Update network timeout

src/hooks/useFreshchat.ts
Problem
=======
- When a failed messages is attempted to resend it does not work
[link to JIRA RGR-654](https://usxtech.atlassian.net/browse/RGR-654)
Solution
========
- Fixed the resending issue for the failed message 
=> RGR-654 When a failed messages is attempted to resend it does not work

src/components/Chat.tsx
Problem
=======
[link to JIRA RGR-559](https://usxtech.atlassian.net/browse/RGR-559)
Solution
========
Fixed a regex for link matching
=> [RGR-559] Fixed Regex for links

src/components/Chat.tsx
Problem
=======
Solution
========
What I/we did to solve this problem
with @pairperson1
=> Fixed lint error

src/components/Chat.tsx
Problem
=======
URLs without protocol are not set as links
[link to JIRA RGR-634](https://usxtech.atlassian.net/browse/RGR-634)
Solution
========
Made URL protocol optional on pattern match
=> RGR-634 URL pattern fix

README.md, src/components/Chat.tsx, src/types/VariantChat.d.ts
Problem
=======
URL links should not be able to launch a browser in all environments
Solution
========
Add a property to disable URL links as needed
=> Add ability to enable/disable url links in chat

package.json, src/components/Bubble.tsx, src/components/Chat.tsx, src/components/MessagePdf.tsx, src/components/VariantChat.tsx, src/hooks/useFreshchat.ts, src/store/selectors/freshchatSelectors.ts, src/store/slices/chat/chat.ts, src/types/VariantChatState.ts
Problem
=======
- Error messages within the ops chat on PS tablet not consistent with ACs
[link to JIRA RGR-688](https://usxtech.atlassian.net/browse/RGR-688)
Solution
========
- Implemented the Freshchat init status
=> RGR-688 Error messages within the ops chat on PS tablet not consistent with ACs

src/components/Chat.tsx
Problem
=======
Link is being handled when links should not be allowed
[link to JIRA RGR-697](https://usxtech.atlassian.net/browse/RGR-697)
Solution
========
Prevent tap and set text style when links not allowed
=> RGR-697 Prevent browser launch on url tap when link not enabled

src/components/Chat.tsx
Problem
=======
[link to JIRA RGR-634](https://usxtech.atlassian.net/browse/RGR-634)
Solution
========
Showing alert if the driver is opening the link in OpsChat
=> [RGR-634] Showing alert if the driver is opening the link in OpsChat

src/components/Chat.tsx, src/components/VariantChat.tsx, src/types/VariantChat.d.ts
Problem
=======
- Updates the link format
[link to JIRA RGR-634](https://usxtech.atlassian.net/browse/RGR-634)
Solution
========
- Updated the link format
=> Updates the link format

package.json
Problem
=======
- Updates the react-native version.
Solution
========
- Updated the react-native version.
=> Updates the react-native version

src/components/Chat.tsx, src/hooks/useAws.ts, src/lib/S3/S3Bucket.ts
Problem
=======
- Updates the AWS S3 configurations
Solution
========
- Updated the AWS S3 configurations for Ops Chat
=> Updates the AWS S3

src/components/Actions.tsx
Problem
=======
Don't want feature right now
[link to JIRA RGR-693](https://usxtech.atlassian.net/browse/RGR-693)
Solution
========
Disable feature
=> RGR-693 Disable add attachment

src/components/MessageText.tsx
Problem
=======
Links in text messages (e.g. phone numbers) are not readable
[link to JIRA RDP-12](https://usxtech.atlassian.net/browse/RDP-12)
Solution
========
Set the link style for message text
=> RDP-12 Set message text link style

src/components/Chat.tsx
Problem
=======
- Removes the console.log
[link to JIRA RDP-10](https://usxtech.atlassian.net/browse/RDP-10)
Solution
========
- Removed the console.log
=> Removes the console.log

src/components/Actions.tsx
Problem
=======
When user clicks on camera its displays and alert with WIP text. 
Solution
========
Removed the icon.
=> RemovedCameraIcon : Removed the camera icon

README.md, package-lock.json, package.json, src/components/Chat.tsx, src/lib/S3/S3Bucket.ts, src/types/VariantChat.d.ts
Problem
=======
Solution
========
What I/we did to solve this problem
with @pairperson1
=> Attachment file name and Attachments disabled by default

src/lib/Freshchat/Freshchat.ts
Problem
=======
Solution
========
What I/we did to solve this problem
with @pairperson1
=> Improve Sentry Logging
